train_params:
  cnt: 'data/cnt'
  sty: 'data/sty'
  ddim_inv_steps: 50
  save_feat_steps: 50
  start_step: 49
  ddim_eta: 0.0
  H: 512
  W: 512
  C: 4
  f: 8
  T: 1.5
  gamma: 0.75
  attn_layer: '6,7,8,9,10,11'
  model_config: 'models/ldm/stable-diffusion-v1/v1-inference.yaml'
  precomputed: './precomputed_feats'
  ckpt: 'models/ldm/stable-diffusion-v1/model.ckpt'
  lora_ckpt_name: 'lora_ckpt_title_lr_g.pth' 
  precision: 'autocast'
  output_path: 'output'
  without_init_adain: False
  without_attn_injection: False
  seed: 22